REM INSERTING into COMPLEMENTARIA
SET DEFINE OFF;
Insert into COMPLEMENTARIA (COD_COMPLEMENTARIA,TIENE_HIJOS,NUMERO_HIJOS,DISCAPACIDAD_FISICA,DISCAPACIDAD_DESC,PUEBLO_INDIGENA,PUEBLO_DESC,POSTULANTE_COD_POSTULANTE,ESTADO_CIVIL) values (1,'0',0,'0',null,'1','Mapuche',1,1);
REM INSERTING into CONTACTO
SET DEFINE OFF;
REM INSERTING into DIRECCION
SET DEFINE OFF;
Insert into DIRECCION (COD_DIRECCION,COD_REGION,COMUNA,DIRECCION,POSTULANTE_COD_POSTULANTE) values (1,3,'comuna1','siempre viva 32',1);
Insert into DIRECCION (COD_DIRECCION,COD_REGION,COMUNA,DIRECCION,POSTULANTE_COD_POSTULANTE) values (2,1,'comuna2','nunca viva 32',2);
Insert into DIRECCION (COD_DIRECCION,COD_REGION,COMUNA,DIRECCION,POSTULANTE_COD_POSTULANTE) values (3,13,'comuna4','a veces viva 32',3);
Insert into DIRECCION (COD_DIRECCION,COD_REGION,COMUNA,DIRECCION,POSTULANTE_COD_POSTULANTE) values (4,3,'comuna3','regular viva 32',4);
REM INSERTING into ESTADO_CIVIL
SET DEFINE OFF;
Insert into ESTADO_CIVIL (COD_ESTADO,ESTADO_CIVIL) values (1,'Soltero');
Insert into ESTADO_CIVIL (COD_ESTADO,ESTADO_CIVIL) values (2,'Casado');
Insert into ESTADO_CIVIL (COD_ESTADO,ESTADO_CIVIL) values (3,'Unión civil');
Insert into ESTADO_CIVIL (COD_ESTADO,ESTADO_CIVIL) values (4,'Separado');
Insert into ESTADO_CIVIL (COD_ESTADO,ESTADO_CIVIL) values (5,'Divorciado');
Insert into ESTADO_CIVIL (COD_ESTADO,ESTADO_CIVIL) values (6,'Viudo');
REM INSERTING into ESTUDIOS
SET DEFINE OFF;
REM INSERTING into EXPERIENCIA_LABORAL
SET DEFINE OFF;
REM INSERTING into INSTITUCION
SET DEFINE OFF;
Insert into INSTITUCION (COD_INSTITUCION,PAIS,INSTITUCION,RANKING,PUNTAJE,POSTULANTE_COD_POSTULANTE,URL) values (1,'USA','Harvard Unversity',1,5000,1,'1');
REM INSERTING into LINEA_INVESTIGACION
SET DEFINE OFF;
REM INSERTING into OBJETIVOS
SET DEFINE OFF;
REM INSERTING into POSTULANTE
SET DEFINE OFF;
Insert into POSTULANTE (COD_POSTULANTE,APELLIDO_PATERNO,APELLIDO_MATERNO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,RUN,FECHA_NACIMIENTO,NACIONALIDAD,SEXO,PASAPORTE_VISA,FECHA_POSTULACION) values (3,'Tapias','Muñoz','Maria','Javiera','134327893',to_date('10/09/92','DD/MM/RR'),'chilena','m','234132',to_date('15/11/20','DD/MM/RR'));
Insert into POSTULANTE (COD_POSTULANTE,APELLIDO_PATERNO,APELLIDO_MATERNO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,RUN,FECHA_NACIMIENTO,NACIONALIDAD,SEXO,PASAPORTE_VISA,FECHA_POSTULACION) values (1,'Soto','Tapía','Ignacio','Martin','124327893',to_date('10/10/90','DD/MM/RR'),'chilena','m','234432',to_date('10/10/20','DD/MM/RR'));
Insert into POSTULANTE (COD_POSTULANTE,APELLIDO_PATERNO,APELLIDO_MATERNO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,RUN,FECHA_NACIMIENTO,NACIONALIDAD,SEXO,PASAPORTE_VISA,FECHA_POSTULACION) values (2,'Fernandez','Muñoz','Clara','Javiera','134327893',to_date('10/09/93','DD/MM/RR'),'chilena','m','234132',to_date('10/11/20','DD/MM/RR'));
Insert into POSTULANTE (COD_POSTULANTE,APELLIDO_PATERNO,APELLIDO_MATERNO,PRIMER_NOMBRE,SEGUNDO_NOMBRE,RUN,FECHA_NACIMIENTO,NACIONALIDAD,SEXO,PASAPORTE_VISA,FECHA_POSTULACION) values (4,'Erazo','Simpson','Michelle',null,'134327893',to_date('31/07/96','DD/MM/RR'),'chilena','m','124132',to_date('15/12/20','DD/MM/RR'));
REM INSERTING into PROYECTO
SET DEFINE OFF;
REM INSERTING into PUNTAJE
SET DEFINE OFF;
REM INSERTING into REGION
SET DEFINE OFF;
Insert into REGION (COD_REGION,REGION) values (1,'Tarapaca');
Insert into REGION (COD_REGION,REGION) values (2,'Antofagasta');
Insert into REGION (COD_REGION,REGION) values (3,'Atacama');
Insert into REGION (COD_REGION,REGION) values (4,'Coquimbo');
Insert into REGION (COD_REGION,REGION) values (5,'Valparaiso');
Insert into REGION (COD_REGION,REGION) values (6,'OHiggins');
Insert into REGION (COD_REGION,REGION) values (7,'Maule');
Insert into REGION (COD_REGION,REGION) values (8,'Biobio');
Insert into REGION (COD_REGION,REGION) values (9,'Araucania');
Insert into REGION (COD_REGION,REGION) values (10,'Lagos');
Insert into REGION (COD_REGION,REGION) values (11,'Aysen');
Insert into REGION (COD_REGION,REGION) values (12,'Magallanes');
Insert into REGION (COD_REGION,REGION) values (13,'Metropolitana');
Insert into REGION (COD_REGION,REGION) values (14,'Los rios');
Insert into REGION (COD_REGION,REGION) values (15,'Arica');
Insert into REGION (COD_REGION,REGION) values (16,'Nuble');
REM INSERTING into SUBAREA
SET DEFINE OFF;
Insert into SUBAREA (COD_SUBAREA,NOMBRE_SUBAREA,INSTITUCION_COD_INSTITUCION) values (1,'CARDIOLOGÍA',1);
REM INSERTING into SUBESPECIALIDAD
SET DEFINE OFF;
Insert into SUBESPECIALIDAD (COD_SUBESPECIALIDAD,NOMBRE,REQUISITO,EXPERIENCIA_LABORAL,IDIOMA,CUPOS,DURACION,SUBAREA_COD_SUBAREA,MODULOS) values (1,'CARDIOLOGÍA','Medicina interna',2,'Inglés','2','2',1,'1');
REM INSERTING into TITULO
SET DEFINE OFF;
