--------------------------------------------------------
-- Archivo creado  - jueves-julio-08-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table COMPLEMENTARIA
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."COMPLEMENTARIA" 
   (	"COD_COMPLEMENTARIA" NUMBER(*,0), 
	"TIENE_HIJOS" CHAR(1 BYTE), 
	"NUMERO_HIJOS" NUMBER(*,0), 
	"DISCAPACIDAD_FISICA" CHAR(1 BYTE), 
	"DISCAPACIDAD_DESC" VARCHAR2(60 CHAR), 
	"PUEBLO_INDIGENA" CHAR(1 BYTE), 
	"PUEBLO_DESC" VARCHAR2(60 CHAR), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0), 
	"ESTADO_CIVIL" NUMBER(*,0) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTACTO
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."CONTACTO" 
   (	"COD_CONTACTO" NUMBER(*,0), 
	"TIPO_DIRECCION" VARCHAR2(60 CHAR), 
	"DIRECCION" VARCHAR2(60 CHAR), 
	"ENVIO_CORRESPONDENCIA" VARCHAR2(60 CHAR), 
	"OPCIONES" VARCHAR2(70 CHAR), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DIRECCION
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."DIRECCION" 
   (	"COD_DIRECCION" NUMBER(*,0), 
	"COD_REGION" NUMBER(*,0), 
	"COMUNA" VARCHAR2(30 CHAR), 
	"DIRECCION" VARCHAR2(30 CHAR), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTADO_CIVIL
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."ESTADO_CIVIL" 
   (	"COD_ESTADO" NUMBER(*,0), 
	"ESTADO_CIVIL" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ESTUDIOS
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."ESTUDIOS" 
   (	"COD_ESTUDIOS" NUMBER(*,0), 
	"PAIS_ESTUDIOS" VARCHAR2(60 CHAR), 
	"DEPENDENCIA_ESTABLECIMIENTO" VARCHAR2(60 CHAR), 
	"TIPO_ESTABLECIMIENTO" VARCHAR2(60 BYTE), 
	"TIPO_INGRESO" VARCHAR2(60 CHAR), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXPERIENCIA_LABORAL
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" 
   (	"COD_EXPERIENCIA" NUMBER(*,0), 
	"TIPO_EXPERENCIA" VARCHAR2(70 CHAR), 
	"NOMBRE_EMPRESA" VARCHAR2(70 CHAR), 
	"FECHA_INICIO" DATE, 
	"FECHA_TERMINO" DATE, 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INSTITUCION
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."INSTITUCION" 
   (	"COD_INSTITUCION" NUMBER(*,0), 
	"PAIS" VARCHAR2(60 CHAR), 
	"INSTITUCION" VARCHAR2(70 CHAR), 
	"RANKING" NUMBER(*,0), 
	"PUNTAJE" NUMBER(*,0), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0), 
	"URL" VARCHAR2(90 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table LINEA_INVESTIGACION
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."LINEA_INVESTIGACION" 
   (	"COD_INVESTIGACION" NUMBER(*,0), 
	"LINEA_1" VARCHAR2(200 CHAR), 
	"LINEA_2" VARCHAR2(200 CHAR), 
	"LINEA_3" VARCHAR2(200 CHAR), 
	"DICIPLINA_PRINCIPAL" VARCHAR2(200 CHAR), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OBJETIVOS
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."OBJETIVOS" 
   (	"COD_OBJETIVO" NUMBER(*,0), 
	"OBJETIVOS" BLOB, 
	"INTERES" BLOB, 
	"RETORNO" BLOB, 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("OBJETIVOS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("INTERES") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("RETORNO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table POSTULANTE
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."POSTULANTE" 
   (	"COD_POSTULANTE" NUMBER(*,0), 
	"APELLIDO_PATERNO" VARCHAR2(30 CHAR), 
	"APELLIDO_MATERNO" VARCHAR2(30 CHAR), 
	"PRIMER_NOMBRE" VARCHAR2(30 CHAR), 
	"SEGUNDO_NOMBRE" VARCHAR2(30 CHAR), 
	"RUN" VARCHAR2(11 CHAR), 
	"FECHA_NACIMIENTO" DATE, 
	"NACIONALIDAD" VARCHAR2(30 CHAR), 
	"SEXO" CHAR(1 BYTE), 
	"PASAPORTE_VISA" VARCHAR2(70 CHAR), 
	"FECHA_POSTULACION" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PROYECTO
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."PROYECTO" 
   (	"COD_PROYECTO" NUMBER(*,0), 
	"TITULO" VARCHAR2(70 CHAR), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PUNTAJE
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."PUNTAJE" 
   (	"COD_PUNTAJE" NUMBER(*,0), 
	"PTJE_EDAD" NUMBER(*,0), 
	"PTJE_ES_CIVIL" NUMBER(*,0), 
	"PTJE_PUEBLO_INDIGENA" NUMBER(*,0), 
	"PTJE_ZONA_EXTREMA" NUMBER(*,0), 
	"PTJE_ANTEC_ACAD" NUMBER(*,0), 
	"PTJE_TRAYEC" NUMBER(*,0), 
	"PTJE_DOCENCIA" NUMBER(*,0), 
	"PTJE_ESTUDIO" NUMBER(*,0), 
	"PTJE_RETRIB" NUMBER(*,0), 
	"PTJE_RANKING" NUMBER(*,0), 
	"PTJE_TOTAL" NUMBER(*,0), 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table REGION
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."REGION" 
   (	"COD_REGION" NUMBER(*,0), 
	"REGION" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBAREA
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."SUBAREA" 
   (	"COD_SUBAREA" NUMBER(*,0), 
	"NOMBRE_SUBAREA" VARCHAR2(70 CHAR), 
	"INSTITUCION_COD_INSTITUCION" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUBESPECIALIDAD
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."SUBESPECIALIDAD" 
   (	"COD_SUBESPECIALIDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(70 CHAR), 
	"REQUISITO" VARCHAR2(70 CHAR), 
	"EXPERIENCIA_LABORAL" NUMBER(*,0), 
	"IDIOMA" VARCHAR2(70 CHAR), 
	"CUPOS" VARCHAR2(70 CHAR), 
	"DURACION" VARCHAR2(70 CHAR), 
	"SUBAREA_COD_SUBAREA" NUMBER(*,0), 
	"MODULOS" VARCHAR2(200 BYTE) DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TITULO
--------------------------------------------------------

  CREATE TABLE "C##POSTULACION"."TITULO" 
   (	"COD_TITULO" NUMBER(*,0), 
	"TIPO_ESTUDIO" VARCHAR2(60 CHAR), 
	"INSTITUCION" VARCHAR2(70 CHAR), 
	"NOMBRE_CARRERA" VARCHAR2(70 CHAR), 
	"FECHA_OBTENCION" DATE, 
	"POSTULANTE_COD_POSTULANTE" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index COMPLEMENTARIA__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."COMPLEMENTARIA__IDX" ON "C##POSTULACION"."COMPLEMENTARIA" ("POSTULANTE_COD_POSTULANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index CONTACTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."CONTACTO_PK" ON "C##POSTULACION"."CONTACTO" ("COD_CONTACTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index DIRECCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."DIRECCION_PK" ON "C##POSTULACION"."DIRECCION" ("COD_DIRECCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTUDIOS__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."ESTUDIOS__IDX" ON "C##POSTULACION"."ESTUDIOS" ("POSTULANTE_COD_POSTULANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index ESTUDIOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."ESTUDIOS_PK" ON "C##POSTULACION"."ESTUDIOS" ("COD_ESTUDIOS") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index EXPERIENCIA_LABORAL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."EXPERIENCIA_LABORAL_PK" ON "C##POSTULACION"."EXPERIENCIA_LABORAL" ("COD_EXPERIENCIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INSTITUCION__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."INSTITUCION__IDX" ON "C##POSTULACION"."INSTITUCION" ("POSTULANTE_COD_POSTULANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index INSTITUCION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."INSTITUCION_PK" ON "C##POSTULACION"."INSTITUCION" ("COD_INSTITUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LINEA_INVESTIGACION__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."LINEA_INVESTIGACION__IDX" ON "C##POSTULACION"."LINEA_INVESTIGACION" ("POSTULANTE_COD_POSTULANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index LINEA_INVESTIGACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."LINEA_INVESTIGACION_PK" ON "C##POSTULACION"."LINEA_INVESTIGACION" ("COD_INVESTIGACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OBJETIVOS__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."OBJETIVOS__IDX" ON "C##POSTULACION"."OBJETIVOS" ("POSTULANTE_COD_POSTULANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OBJETIVOS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."OBJETIVOS_PK" ON "C##POSTULACION"."OBJETIVOS" ("COD_OBJETIVO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index POSTULANTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."POSTULANTE_PK" ON "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PROYECTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."PROYECTO_PK" ON "C##POSTULACION"."PROYECTO" ("COD_PROYECTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PUNTAJE__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."PUNTAJE__IDX" ON "C##POSTULACION"."PUNTAJE" ("POSTULANTE_COD_POSTULANTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PUNTAJE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."PUNTAJE_PK" ON "C##POSTULACION"."PUNTAJE" ("COD_PUNTAJE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBAREA__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."SUBAREA__IDX" ON "C##POSTULACION"."SUBAREA" ("INSTITUCION_COD_INSTITUCION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBAREA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."SUBAREA_PK" ON "C##POSTULACION"."SUBAREA" ("COD_SUBAREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SUBESPECIALIDAD__IDX
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."SUBESPECIALIDAD__IDX" ON "C##POSTULACION"."SUBESPECIALIDAD" ("SUBAREA_COD_SUBAREA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index TITULO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##POSTULACION"."TITULO_PK" ON "C##POSTULACION"."TITULO" ("COD_TITULO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table COMPLEMENTARIA
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."COMPLEMENTARIA" MODIFY ("COD_COMPLEMENTARIA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."COMPLEMENTARIA" MODIFY ("TIENE_HIJOS" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."COMPLEMENTARIA" MODIFY ("DISCAPACIDAD_FISICA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."COMPLEMENTARIA" MODIFY ("PUEBLO_INDIGENA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."COMPLEMENTARIA" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."COMPLEMENTARIA" MODIFY ("ESTADO_CIVIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CONTACTO
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."CONTACTO" MODIFY ("COD_CONTACTO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."CONTACTO" MODIFY ("TIPO_DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."CONTACTO" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."CONTACTO" MODIFY ("ENVIO_CORRESPONDENCIA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."CONTACTO" MODIFY ("OPCIONES" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."CONTACTO" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."CONTACTO" ADD CONSTRAINT "CONTACTO_PK" PRIMARY KEY ("COD_CONTACTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DIRECCION
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."DIRECCION" MODIFY ("COD_DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."DIRECCION" MODIFY ("COD_REGION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."DIRECCION" MODIFY ("COMUNA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."DIRECCION" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."DIRECCION" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."DIRECCION" ADD CONSTRAINT "DIRECCION_PK" PRIMARY KEY ("COD_DIRECCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ESTADO_CIVIL
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."ESTADO_CIVIL" MODIFY ("COD_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."ESTADO_CIVIL" MODIFY ("ESTADO_CIVIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTUDIOS
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."ESTUDIOS" MODIFY ("COD_ESTUDIOS" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."ESTUDIOS" MODIFY ("PAIS_ESTUDIOS" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."ESTUDIOS" MODIFY ("TIPO_ESTABLECIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."ESTUDIOS" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."ESTUDIOS" ADD CONSTRAINT "ESTUDIOS_PK" PRIMARY KEY ("COD_ESTUDIOS")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table EXPERIENCIA_LABORAL
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" MODIFY ("COD_EXPERIENCIA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" MODIFY ("TIPO_EXPERENCIA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" MODIFY ("FECHA_INICIO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" MODIFY ("FECHA_TERMINO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" ADD CONSTRAINT "EXPERIENCIA_LABORAL_PK" PRIMARY KEY ("COD_EXPERIENCIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table INSTITUCION
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."INSTITUCION" MODIFY ("COD_INSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."INSTITUCION" MODIFY ("PAIS" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."INSTITUCION" MODIFY ("INSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."INSTITUCION" MODIFY ("RANKING" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."INSTITUCION" MODIFY ("PUNTAJE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."INSTITUCION" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."INSTITUCION" ADD CONSTRAINT "INSTITUCION_PK" PRIMARY KEY ("COD_INSTITUCION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "C##POSTULACION"."INSTITUCION" MODIFY ("URL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LINEA_INVESTIGACION
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" MODIFY ("COD_INVESTIGACION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" MODIFY ("LINEA_1" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" MODIFY ("LINEA_2" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" MODIFY ("LINEA_3" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" MODIFY ("DICIPLINA_PRINCIPAL" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" ADD CONSTRAINT "LINEA_INVESTIGACION_PK" PRIMARY KEY ("COD_INVESTIGACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table OBJETIVOS
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."OBJETIVOS" MODIFY ("COD_OBJETIVO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."OBJETIVOS" MODIFY ("OBJETIVOS" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."OBJETIVOS" MODIFY ("INTERES" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."OBJETIVOS" MODIFY ("RETORNO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."OBJETIVOS" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."OBJETIVOS" ADD CONSTRAINT "OBJETIVOS_PK" PRIMARY KEY ("COD_OBJETIVO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table POSTULANTE
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("APELLIDO_PATERNO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("APELLIDO_MATERNO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("PRIMER_NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("RUN" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("FECHA_NACIMIENTO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("NACIONALIDAD" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("SEXO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("PASAPORTE_VISA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" MODIFY ("FECHA_POSTULACION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."POSTULANTE" ADD CONSTRAINT "POSTULANTE_PK" PRIMARY KEY ("COD_POSTULANTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PROYECTO
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."PROYECTO" MODIFY ("COD_PROYECTO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PROYECTO" MODIFY ("TITULO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PROYECTO" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PROYECTO" ADD CONSTRAINT "PROYECTO_PK" PRIMARY KEY ("COD_PROYECTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table PUNTAJE
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("COD_PUNTAJE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_EDAD" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_ES_CIVIL" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_PUEBLO_INDIGENA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_ZONA_EXTREMA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_ANTEC_ACAD" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_TRAYEC" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_DOCENCIA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_ESTUDIO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_RETRIB" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_RANKING" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("PTJE_TOTAL" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."PUNTAJE" ADD CONSTRAINT "PUNTAJE_PK" PRIMARY KEY ("COD_PUNTAJE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table REGION
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."REGION" MODIFY ("COD_REGION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."REGION" MODIFY ("REGION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SUBAREA
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."SUBAREA" MODIFY ("COD_SUBAREA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBAREA" MODIFY ("NOMBRE_SUBAREA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBAREA" MODIFY ("INSTITUCION_COD_INSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBAREA" ADD CONSTRAINT "SUBAREA_PK" PRIMARY KEY ("COD_SUBAREA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SUBESPECIALIDAD
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("COD_SUBESPECIALIDAD" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("REQUISITO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("EXPERIENCIA_LABORAL" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("IDIOMA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("CUPOS" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("DURACION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("MODULOS" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" MODIFY ("SUBAREA_COD_SUBAREA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TITULO
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."TITULO" MODIFY ("COD_TITULO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."TITULO" MODIFY ("TIPO_ESTUDIO" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."TITULO" MODIFY ("INSTITUCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."TITULO" MODIFY ("NOMBRE_CARRERA" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."TITULO" MODIFY ("FECHA_OBTENCION" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."TITULO" MODIFY ("POSTULANTE_COD_POSTULANTE" NOT NULL ENABLE);
  ALTER TABLE "C##POSTULACION"."TITULO" ADD CONSTRAINT "TITULO_PK" PRIMARY KEY ("COD_TITULO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table COMPLEMENTARIA
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."COMPLEMENTARIA" ADD CONSTRAINT "COMPLEMENTARIA_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table CONTACTO
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."CONTACTO" ADD CONSTRAINT "CONTACTO_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DIRECCION
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."DIRECCION" ADD CONSTRAINT "DIRECCION_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ESTUDIOS
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."ESTUDIOS" ADD CONSTRAINT "ESTUDIOS_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EXPERIENCIA_LABORAL
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."EXPERIENCIA_LABORAL" ADD CONSTRAINT "EXP_LABORAL_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table INSTITUCION
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."INSTITUCION" ADD CONSTRAINT "INSTITUCION_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LINEA_INVESTIGACION
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."LINEA_INVESTIGACION" ADD CONSTRAINT "LINEA_INVEST_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table OBJETIVOS
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."OBJETIVOS" ADD CONSTRAINT "OBJETIVOS_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROYECTO
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."PROYECTO" ADD CONSTRAINT "PROYECTO_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PUNTAJE
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."PUNTAJE" ADD CONSTRAINT "PUNTAJE_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBAREA
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."SUBAREA" ADD CONSTRAINT "SUBAREA_INSTITUCION_FK" FOREIGN KEY ("INSTITUCION_COD_INSTITUCION")
	  REFERENCES "C##POSTULACION"."INSTITUCION" ("COD_INSTITUCION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SUBESPECIALIDAD
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."SUBESPECIALIDAD" ADD CONSTRAINT "SUBESPECIALIDAD_SUBAREA_FK" FOREIGN KEY ("SUBAREA_COD_SUBAREA")
	  REFERENCES "C##POSTULACION"."SUBAREA" ("COD_SUBAREA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TITULO
--------------------------------------------------------

  ALTER TABLE "C##POSTULACION"."TITULO" ADD CONSTRAINT "TITULO_POSTULANTE_FK" FOREIGN KEY ("POSTULANTE_COD_POSTULANTE")
	  REFERENCES "C##POSTULACION"."POSTULANTE" ("COD_POSTULANTE") ENABLE;
